### ISSUE TITLE
Unstable TravisCI builds

### ISSUE THREAD

**Issue by lmars** [flynn-archive/ruby-discoverd#15]
TravisCI [build 47](https://travis-ci.org/flynn/ruby-discoverd/builds/19666146) failed on a single Ruby version, even though the only change was to CONTRIBUTING.md.

There is likely a sneaky race condition bug somewhere, I'll try and track it down.

**Comment by lmars** [comment]
Looks like it's because we are not sleeping long enough in the tests (e.g. [here](https://github.com/flynn/ruby-discoverd/blob/master/test/integration/test_service_leader.rb#L36)).

I'll add a method like `wait_or_timeout(update_count)` which waits for updates or times out after say 3 seconds

**Comment by titanous** [comment]
Yeah, that's what I did in the Go tests.
