### ISSUE TITLE
Add Travis CI config

### ISSUE THREAD

**Issue by titanous** [flynn-archive/ruby-discoverd#4]

**Comment by lmars** [comment]
@titanous I've added a `.travis.yml` file to the `travis-ci` branch (see [here](https://github.com/flynn/discoverd-ruby/blob/travis-ci/.travis.yml)), can you enable TravisCI for the repo?

**Comment by titanous** [comment]
@lmars done.

**Comment by lmars** [comment]
Travis CI added in #6, closing
